### ISSUE TITLE
parameters.tsv 

### ISSUE THREAD

**Issue by shaharjacob** [Aunsiels/CSK#1]
Hi,
Is it possible to share a parameters.tsv for example? (in addition to the template)

Thanks,
Shahar

**Comment by Aunsiels** [comment]
Here is my latest parameters.tsv. The key and the value must be separated by a tab.

bing-key       YOUR_KEY
google-book-key YOUR_KEY
openie-file     data/openie5_results.txt
openie-file-no-found    data/no_found_openie_sentences.txt
default-mongodb-location        mongodb://localhost:5000/
conceptnet-subjects     data/subjects_20k.txt
animal-subjects data/anitemp.txt
wikidata-subjects       data/wikidata_subjects.txt
occupations-subjects    data/occupations_50.txt
flickr-clusters data/assos_flickr_clusters.tsv
imagetag-associations   data/assos_imagestags_openimage.tsv
pattern-first   true
out-dir out/
question-cache-dir      question2statement/
memory-corenlp  16G
conceptual-caption-file data/conceptual_captions.txt
what-questions-file     data/what_questions.txt
answercom-questions     data/questions-answerscom-filtered.txt
quora-questions questions-quora.txt
reddit-questions        data/why-how-questions-filtered.txt
yahoo-questions data/questions-yahoo.txt
stats-snippets  data/stats_animal_occupations_snippets.tsv
cache-corenlp   data/cache_corenlp.tsv
properties-dir  data/properties/
annotations-file        data/all_manual_annotations.tsv
server-url      http://localhost:1050/
perplexity-file perplexity/sentences_ppl.tsv


I am not sure running the code is that easy. The part that gets new questions is not always running to speed up the pipeline. If you want to get new question from a search engine, you must put pattern-first to false. You can also run a server and multiple client for that with https://github.com/Aunsiels/CSK/blob/master/quasimodo/assertion_generation/browser_autocomplete_server.py and https://github.com/Aunsiels/CSK/blob/master/quasimodo/assertion_generation/google_autocomplete_client.py. You can give the same parameters.tsv file, with pattern_first set to false.
